"""FastMCP application instance — imported by all tool modules."""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP(
    "sysinternals-mcp",
    instructions=(
        "Wrap the Microsoft Sysinternals tool suite for Windows process "
        "introspection, binary triage, ACL audit, and event-trace capture. "
        "The server ships ZERO Sysinternals binaries -- the operator "
        "downloads them from learn.microsoft.com/en-us/sysinternals/ and "
        "points the server at the install dir via SYSINTERNALS_MCP_DIR.\n"
        "\n"
        "SETUP: call `check_sysinternals_setup` once after install. The "
        "table lists every Sysinternals binary the server knows about, "
        "where it was found, and whether the EULA is accepted under the "
        "current user. For any not-accepted row the Action column "
        "contains a paste-ready `reg add` command. Re-run after pasting "
        "to confirm.\n"
        "\n"
        "LIVE TOOLS: `handle_list`, `sigcheck`, `pslist`, `accesschk`. "
        "Each takes `target='local'` (server runs the binary as a "
        "subprocess on this machine and returns parsed markdown) or "
        "`target='remote'` (server returns the exact command line as a "
        "fenced ```powershell``` block -- the operator runs it on the "
        "remote target via any transport and pipes the stdout back into "
        "the matching `parse_<tool>_output` tool).\n"
        "\n"
        "PROCMON CAPTURE: `list_procmon_recipes` for the bundled "
        "filter recipes (file_io_only / network_only / process_lifecycle). "
        "`get_procmon_recipe(recipe)` for the recipe contents. "
        "`get_procmon_capture_commands(recipe, output_path, duration_s)` "
        "for the 3-step start/sleep/stop commands. "
        "`get_capture_instructions(recipe, target, output_path)` for the "
        "long-form runbook including transfer-back examples for remote "
        "targets (PowerShell remoting, MCP file-transfer tools such as "
        "LabLink, manual scp).\n"
        "\n"
        "PML ANALYSIS: `analyze_pml(path)` decodes a ProcMon .pml file "
        "by shelling out to procmon.exe /OpenLog /SaveAs CSV then "
        "summarizing with pandas (top processes, op-class histogram, "
        "error count).\n"
        "\n"
        "FEDERATION: `get_evidence_status` and `get_entities` are no-ops "
        "by default. Enable by installing the optional `evidence-store` "
        "library AND setting `SYSINTERNALS_MCP_EVIDENCE_PATH`.\n"
        "\n"
        "REMOTE-AGNOSTIC: NOTHING in this MCP is coupled to any "
        "particular remote-execution MCP. LabLink is named in docs as "
        "ONE example transport, alongside PowerShell remoting and "
        "manual scp."
    ),
)
